// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55iy1cY6knbgxmd_Bhw2YahP53XjfFl0',
    appId: '1:1069471458207:web:2dd670160ef160945b93aa',
    messagingSenderId: '1069471458207',
    projectId: 'empowr-7be3e',
    authDomain: 'empowr-7be3e.firebaseapp.com',
    storageBucket: 'empowr-7be3e.appspot.com',
    measurementId: 'G-9PS7Q8THJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv05iRjKo7BOLWFnPUr2jzJePUo1-rPIU',
    appId: '1:1069471458207:android:441de07fbcb9caf55b93aa',
    messagingSenderId: '1069471458207',
    projectId: 'empowr-7be3e',
    storageBucket: 'empowr-7be3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCD4EuaaIpJBU2K0IooWZbJ8p0_8gUW_w',
    appId: '1:1069471458207:ios:ce898c7a36d19ef55b93aa',
    messagingSenderId: '1069471458207',
    projectId: 'empowr-7be3e',
    storageBucket: 'empowr-7be3e.appspot.com',
    iosClientId: '1069471458207-lc753bobnquiv3308baer0vknqhnrvg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.empowr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCD4EuaaIpJBU2K0IooWZbJ8p0_8gUW_w',
    appId: '1:1069471458207:ios:5885e149d54e28e15b93aa',
    messagingSenderId: '1069471458207',
    projectId: 'empowr-7be3e',
    storageBucket: 'empowr-7be3e.appspot.com',
    iosClientId: '1069471458207-g8a8rdp92240n3l53ohra1stm5igddmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.empowr.RunnerTests',
  );
}
